# Generated by Django 5.0.6 on 2024-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='telegram_id',
            field=models.IntegerField(default=0),
        ),
    ]
