# Generated by Django 5.0.6 on 2024-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_entities_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entities',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
