# Generated by Django 5.0.6 on 2024-05-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_additionalsourcesmodels_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalsourcesmodels',
            old_name='visiters',
            new_name='visitors',
        ),
    ]
