# Generated by Django 5.0.6 on 2024-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='profile/nouserimage.jpg', upload_to='profile/profile_pics'),
        ),
    ]
